name: Build Arvan Xray Portal

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./arvan-xray-portal
          file: ./arvan-xray-portal/Dockerfile
          push: true
          platforms: linux/amd64
          provenance: false
          sbom: false
          tags: |
            ghcr.io/bloodyassult/arvan-xray-portal:0.2
            dsebg/arvan-xray-portal:0.2
